services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rent_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: rent_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    expose:
      - 3306

  web:
    container_name: rent_web
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  node:
    image: node:22
    container_name: rent_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
    environment:
      - NODE_ENV=development
    ports:
      - '5173:5173'
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: {}
